import { Geolocation } from "./Geolocation";

// Generated by https://quicktype.io

export class Meteor {

    Fall:                           string;
    Geolocation:                   Geolocation;
    Id:                             string;
    Mass:                          number;
    Name:                           string;
    Nametype:                       string;
    Recclass:                       string;
    Reclat:                        string;
    Reclong:                       string;
    Year:                          Date;
}

